### ISSUE TITLE
Please add a way to ignore/disable Rules

### ISSUE THREAD

**Issue by KeyboardInterrupt** [jonlabelle/SublimeLinter-contrib-markdownlint#1]
Hi, I really like your linter package,
I started using it today, and it already made my Markdown a lot more beautiful ;)

The only thing that i find distracting is the Line length rule, and I would love to be able to disable Rules like that.

Have you planed to add a way to control this behavior?

**Comment by jonlabelle** [comment]
Simply create a `.markdownlint` file, and add the [line-length](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013---line-length) rule.

Here's an [example](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/.markdownlintrc#L4).

**Comment by KeyboardInterrupt** [comment]
Thank  you :+1:
