### ISSUE TITLE
RangeError being thrown in debug console

### ISSUE THREAD

**Issue by craigmac** [jonlabelle/SublimeLinter-contrib-markdownlint#13]
I can run `which markdownlint` from CLI just fine and run `markdownlint components.md` will produce results, but I can't get those results in ST4106. 

Here is what is think is the relevant output:

```
SublimeLinter: #3 linter.py:1623      Running ...

  /Users/cmaceach/git/devx  (working dir)
  $ /Users/cmaceach/.nvm/versions/node/v12.22.1/bin/markdownlint /var/folders/bx/1jy73ln93x5fc0kpdxmgxr780000gp/T/tmpirdhcu.md

SublimeLinter: #3 linter.py:1189      markdownlint: output:
  /Users/cmaceach/.nvm/versions/node/v12.22.1/lib/node_modules/markdownlint-cli/node_modules/ignore/index.js:366
    throw new Ctor(message)
    ^

  RangeError: path should be a `path.relative()`d string, but got "../../../../var/folders/bx/1jy73ln93x5fc0kpdxmgxr780000gp/T/tmpirdhcu.md"
      at throwError (/Users/cmaceach/.nvm/versions/node/v12.22.1/lib/node_modules/markdownlint-cli/node_modules/ignore/index.js:366:9)
```

Any ideas? Here is my SublimeLinter.sublime-settings file:

```
{
    "debug": true,
    "paths": {
        "osx": ["~/.nvm/versions/node/v12.22.1/bin", "~/.rbenv/shims"]
    },
    "linters": {
        "markdownlint": {
            "env": {"PATH":"~/.nvm/versions/node/v12.22.1/bin"}
        }
    }

}
```

**Comment by jonlabelle** [comment]
Hi @craigmac. I'm not very familiar with NVM, but I'll try... a couple things stand out in your **SublimeLinter.sublime-settings** file:

1. line no. 4: `"osx": ["~/.nvm/versions/node/v12.22.1/bin", "~/.rbenv/shims"]`  
    - The same path is essentially added twice to the environment (see line no. 8); though unclear if this could cause issues
2. line no. 8: `"env": {"PATH":"~/.nvm/versions/node/v12.22.1/bin"}`  
    - On the same page, if `~/.nvm/versions/node/v12.22.1/bin` is already in your `$PATH`, try taking out taking the `env` setting entirely (line no. 8)
