### ISSUE TITLE
It does not work ! Did i do something wrong ?

### ISSUE THREAD

**Issue by ghost** [jonlabelle/SublimeLinter-contrib-markdownlint#4]
System : Manjaro 
node version : .nvm/versions/node/v10.14.2
sublime-text version : 3.1.1 (3176)
I use package control installed SublimeLinter , SublimeLinter-contrib-markdownlint , npm install markdownlint-cli -g . I also use oh-my-zsh . I use nvm installed nodejs . in my .zshrc ,there is only one line `source /usr/share/nvm/init-nvm.sh` . Do i need to create .markdownlintrc file myself ? Is there a default ?

**Comment by jonlabelle** [comment]
I'm not familiar w/ NVM - but to answer your question regarding `.markdownlintrc`... there is no "defaut" file created. Please refer to the markdownlint documentation for more info.

**Comment by ghost** [comment]
@jonlabelle `markdownlint --config .markdownlintrc mymarkdown.md`  works fine . But not in sublime-text .  
My `SublimeLinter.sublime.settings - users `
```
{
	"debug": true,
"linters": {
        "markdownlint": {
            "args": ["--config", "/home/SeAL80s/.markdownlintrc"],
            "lint_mode": "background",
            "selector": "source.md"
        },
        "paths": {
        "linux": ["/home/SeAL80s/.nvm/versions/node/v10.15.0/bin/markdownlint"],
        "osx": [],
        "windows": []
    	},

    },
    "statusbar.show_active_linters": true
}
```
Is this right ?  
In markdown file , `Lint This View` shows
```
SublimeLinter: sublime_linter.py:252  Delay linting 'mymarkdown.md' for 0.0s
```
No errors , no warnings .

**Comment by jonlabelle** [comment]
@SeAL80s: I think you just need to take out the `markdownlint` executable from your **paths > linux** config - I'm pretty sure this value needs *directory* path, not an executable path.

Also, you can probably remove the `markdownlint` config from your `SublimeLinter.sublime-settings setting` all together - since you are just overriding the defaults with the same values configured internally.

e.g.:

```
{
    "debug": true,
    "linters": {
        // Comment/remove these settings as they aren't needed, and are already the defaults:
        // "markdownlint": {
        //     "args": ["--config", "/home/SeAL80s/.markdownlintrc"],
        //     "lint_mode": "background",
        //     "selector": "source.md"
        // },
        "paths": {
            "linux": [
                // Remove the trailing 'markdownlint' executable...
                // this value needs to be a directory search path:
                "/home/SeAL80s/.nvm/versions/node/v10.15.0/bin"
            ],
            "osx": [],
            "windows": []
        }
    },
    "statusbar.show_active_linters": true
}
```
